--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      UNAM
-- Project :      RAVEN-PEOPLE.DM1
-- Author :       Jorge
--
-- Date Created : Sunday, July 15, 2018 19:22:19
-- Target DBMS : Oracle 11g
--

-- 
-- SEQUENCE: CAREER_PLAN_STUDENT_SEQ 
--

CREATE SEQUENCE CAREER_PLAN_STUDENT_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- SEQUENCE: COURSE_PROFESSOR_SEQ 
--

CREATE SEQUENCE COURSE_PROFESSOR_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- SEQUENCE: USER_SEQ 
--

CREATE SEQUENCE USER_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- SEQUENCE: USER_SOCIAL_MEDIA_SEQ 
--

CREATE SEQUENCE USER_SOCIAL_MEDIA_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- TABLE: ADMIN 
--

CREATE TABLE ADMIN(
    USER_ID    NUMBER(10, 0)    NOT NULL,
    ACTIVE     NUMBER(1, 0),
    CONSTRAINT PK4 PRIMARY KEY (USER_ID)
)
;



-- 
-- TABLE: CAREER_PLAN_STUDENT 
--

CREATE TABLE CAREER_PLAN_STUDENT(
    CAREER_PLAN_STUDENT_ID    NUMBER(10, 0)    NOT NULL,
    CAREER_PLAN_ID            NUMBER(10, 0)    NOT NULL,
    USER_ID                   NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK6 PRIMARY KEY (CAREER_PLAN_STUDENT_ID)
)
;



-- 
-- TABLE: COURSE_PROFESSOR 
--

CREATE TABLE COURSE_PROFESSOR(
    COURSE_PROFESSOR_ID    NUMBER(10, 0)    NOT NULL,
    COURSE_ID              NUMBER(10, 0)    NOT NULL,
    USER_ID                NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK5 PRIMARY KEY (COURSE_PROFESSOR_ID)
)
;



-- 
-- TABLE: PROFESSOR 
--

CREATE TABLE PROFESSOR(
    USER_ID    NUMBER(10, 0)    NOT NULL,
    PHOTO      BLOB             NOT NULL,
    ACTIVE     NUMBER(1, 0)     NOT NULL,
    CONSTRAINT PK2 PRIMARY KEY (USER_ID)
)
;



-- 
-- TABLE: SOCIAL_MEDIA 
--

CREATE TABLE SOCIAL_MEDIA(
    SOCIAL_MEDIA_ID    NUMBER(2, 0)     NOT NULL,
    NAME               VARCHAR2(40)     NOT NULL,
    DESCRIPTION        VARCHAR2(100)    NOT NULL,
    ACTIVE             NUMBER(1, 0)     NOT NULL,
    CONSTRAINT PK7 PRIMARY KEY (SOCIAL_MEDIA_ID)
)
;



-- 
-- TABLE: STUDENT 
--

CREATE TABLE STUDENT(
    USER_ID    NUMBER(10, 0)    NOT NULL,
    ACTIVE     NUMBER(1, 0)     NOT NULL,
    CONSTRAINT PK3 PRIMARY KEY (USER_ID)
)
;



-- 
-- TABLE: USER 
--

CREATE TABLE USER(
    USER_ID             NUMBER(10, 0)    NOT NULL,
    NAME                VARCHAR2(100),
    LAST_NAME           VARCHAR2(10),
    SECOND_LAST_NAME    VARCHAR2(100),
    EMAIL               VARCHAR2(200)    NOT NULL,
    PASSWORD            VARCHAR2(20),
    BIRTH_DATE          DATE,
    START_DATE          TIMESTAMP(6),
    IS_STUDENT          NUMBER(1, 0)     NOT NULL,
    IS_PROFESSOR        NUMBER(1, 0)     NOT NULL,
    IS_ADMIN            NUMBER(1, 0)     NOT NULL,
    CONSTRAINT PK1 PRIMARY KEY (USER_ID)
)
;



-- 
-- TABLE: USER_SOCIAL_MEDIA 
--

CREATE TABLE USER_SOCIAL_MEDIA(
    USER_SOCIAL_MEDIA_ID    NUMBER(10, 0)     NOT NULL,
    URL                     VARCHAR2(4000)    NOT NULL,
    SOCIAL_MEDIA_ID         NUMBER(2, 0)      NOT NULL,
    CONSTRAINT PK8 PRIMARY KEY (USER_SOCIAL_MEDIA_ID)
)
;



-- 
-- TABLE: ADMIN 
--

ALTER TABLE ADMIN ADD CONSTRAINT RefUSER6 
    FOREIGN KEY (USER_ID)
    REFERENCES USER(USER_ID)
;


-- 
-- TABLE: CAREER_PLAN_STUDENT 
--

ALTER TABLE CAREER_PLAN_STUDENT ADD CONSTRAINT RefSTUDENT8 
    FOREIGN KEY (USER_ID)
    REFERENCES STUDENT(USER_ID)
;


-- 
-- TABLE: COURSE_PROFESSOR 
--

ALTER TABLE COURSE_PROFESSOR ADD CONSTRAINT RefPROFESSOR7 
    FOREIGN KEY (USER_ID)
    REFERENCES PROFESSOR(USER_ID)
;


-- 
-- TABLE: PROFESSOR 
--

ALTER TABLE PROFESSOR ADD CONSTRAINT RefUSER1 
    FOREIGN KEY (USER_ID)
    REFERENCES USER(USER_ID)
;


-- 
-- TABLE: STUDENT 
--

ALTER TABLE STUDENT ADD CONSTRAINT RefUSER5 
    FOREIGN KEY (USER_ID)
    REFERENCES USER(USER_ID)
;


-- 
-- TABLE: USER_SOCIAL_MEDIA 
--

ALTER TABLE USER_SOCIAL_MEDIA ADD CONSTRAINT RefSOCIAL_MEDIA9 
    FOREIGN KEY (SOCIAL_MEDIA_ID)
    REFERENCES SOCIAL_MEDIA(SOCIAL_MEDIA_ID)
;


